type: openai_gen
model: gpt-4o-mini-2024-07-18
# model: gpt-3.5-turbo-1106
# model: "gpt-4-1106-preview"
system_msg: "You are an expert data-to-text system. You understand structured data and you can correctly operate with units and numerical values. You are designed to output plain text summaries from structured data input."
start_with: "Sure, here is the required output:\n\""
extra_args:
  remove_suffix: '"'
prompt_template: |
  Given the data:
  ```
  {data}
  ```
  Generate a summary in plain text, describing facts and values contained in the input:

  *Example:*
  data:
  ```
  Nokia 3310
  -----
  - **color**: black, blue, grey
  - **display**: 320x240px
  ```
  output (product description):
  ```
  Nokia 3310 features a 320x240 display. It is available in black, blue and grey color.
  ```
  Do not add or fabricate any detail not reflected in the data. Also do not be too strict: some facts can be less specific than in the data (rounded values, shortened or abbreviated text, etc.).
